<a href="https://colab.research.google.com/github/Malvocado/Machine_Learing_Final_Project/blob/main/Feature_Processing_for_attempt_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('BMW_sales_data_after_processing.csv')

Filter year feature to only in range 2022-2024, because in there are too many record in the previous dataset

In [ ]:
df = df[(df['Year'] >= 2022) & (df['Year'] <= 2024)].reset_index(drop=True)
display(df.head())

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
1,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
2,i8,2022,Europe,White,Diesel,Manual,1.8,196741,55064,7949,High
3,X3,2023,Middle East,White,Electric,Automatic,4.1,194398,85370,4645,Low
4,X1,2022,Middle East,Grey,Hybrid,Manual,4.3,143013,116432,4926,Low

Check df's shape after filtered

In [ ]:
print(f"Shape of the filtered DataFrame: {df.shape}")

Shape of the filtered DataFrame: (10124, 11)

Check Unique value

In [ ]:
print(f"Unique years in the filtered DataFrame: {df['Year'].unique()}")

Unique years in the filtered DataFrame: [2022 2024 2023]

## Dataset Analysis & Transformation
We will analyze the 'Year' column distribution and then calculate the age of the records relative to the year 2026.

### Convert Year to Relative Age
Transforming the year format from a specific year (e.g., 2022) to the number of years relative to 2024 (Highest year in the dataset).

In [ ]:
HIGHEST_YEAR = 2024
df['Years_Relative'] = HIGHEST_YEAR - df['Year']

print(f"Sample of transformation (Relative to {CURRENT_YEAR}):")
display(df[['Year', 'Years_Relative']].head())

Sample of transformation (Relative to 2024):

   Year  Years_Relative
0  2022               2
1  2024               0
2  2022               2
3  2023               1
4  2022               2

In [ ]:
print(f"Filtered Feature: ",df['Years_Relative'].head())
print(f"\nWhole dataset: ", df.head())

Filtered Feature:  0    2
1    0
2    2
3    1
4    2
Name: Years_Relative, dtype: int64

Whole dataset:        Model  Year         Region  Color Fuel_Type Transmission  Engine_Size_L  \
0  5 Series  2022  North America   Blue    Petrol    Automatic            4.5
1        X3  2024    Middle East   Blue    Petrol    Automatic            1.7
2        i8  2022         Europe  White    Diesel       Manual            1.8
3        X3  2023    Middle East  White  Electric    Automatic            4.1
4        X1  2022    Middle East   Grey    Hybrid       Manual            4.3

   Mileage_KM  Price_USD  Sales_Volume Sales_Classification  Years_Relative
0       10991     113265          6994                  Low               2
1       27255      60971          4047                  Low               0
2      196741      55064          7949                 High               2
3      194398      85370          4645                  Low               1
4      143013     116432          4926                  Low               2

###Droping region column by filter dataset to only asia

In [ ]:
# Filter the dataset to only include 'Asia'
df = df[df['Region'] == 'Asia']

# Drop the 'Region' column
df = df.drop(columns=['Region'])
df = df.reset_index(drop=True)

# Display the results
print(f"Shape after filtering for Asia: {df.shape}")
display(df.head())

Shape after filtering for Asia: (1703, 11)

,Model,Year,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification,Years_Relative
0,5 Series,2024,Blue,Electric,Manual,3.7,157789,86855,648,Low,0
1,X6,2022,White,Electric,Manual,1.9,182027,35951,3389,Low,2
2,X5,2024,Blue,Hybrid,Automatic,2.6,120597,95900,8581,High,0
3,M3,2022,Blue,Diesel,Manual,1.8,189688,38811,7337,High,2
4,X3,2022,Black,Diesel,Manual,4.0,160878,53997,2162,Low,2

### Final Result

In [ ]:
print(f"Dataset Shape:",df.shape)
print(f"All columns:",df.columns.to_list())
print(df.head())

Dataset Shape: (1703, 11)
All columns: ['Model', 'Year', 'Color', 'Fuel_Type', 'Transmission', 'Engine_Size_L', 'Mileage_KM', 'Price_USD', 'Sales_Volume', 'Sales_Classification', 'Years_Relative']
      Model  Year  Color Fuel_Type Transmission  Engine_Size_L  Mileage_KM  \
0  5 Series  2024   Blue  Electric       Manual            3.7      157789
1        X6  2022  White  Electric       Manual            1.9      182027
2        X5  2024   Blue    Hybrid    Automatic            2.6      120597
3        M3  2022   Blue    Diesel       Manual            1.8      189688
4        X3  2022  Black    Diesel       Manual            4.0      160878

   Price_USD  Sales_Volume Sales_Classification  Years_Relative
0      86855           648                  Low               0
1      35951          3389                  Low               2
2      95900          8581                 High               0
3      38811          7337                 High               2
4      53997          2162                  Low               2

Exporting The dataset

In [ ]:
output_filename = 'BMW_sales_asia_2022_2024.csv'

df.to_csv(output_filename, index=False)

print(f"Successfully exported dataset to {output_filename}")

Successfully exported dataset to BMW_sales_asia_2022_2024.csv